### ISSUE TITLE
Release .exe file not working

### ISSUE THREAD

**Issue by dieguscl** [iterativ/openopc2#64]
**Describe the bug**
I downloaded the `OpenOpcService.exe` from the latest release (0.1.17) and I got the following error when trying to retrieve data after installing it:
![image](https://github.com/user-attachments/assets/447ea483-1669-421d-8854-7df9014b0f2b)

I fixed it by rebuilding all the .exe files using the [`build_executables.ps1`](https://github.com/iterativ/openopc2/blob/develop/scripts/build_executables.ps1) file, and doing the same process, everything worked as expected

**To Reproduce**
1.  Download  `OpenOpcService.exe` and  `OpenOpcCli.exe` from release `0.1.17`
2.  Download `gbda_aut.dll` on the `lib` folder of the repo. Then run `regsvr32 gbda_aut.dll`
3.  Introduce `OPC_GATE_HOST=<your_ip_address>` to the windows system variables
4. `openopcservice install` and `openopcservice start`
5. `openopccli list-servers` will throw the error I mentioned

**Expected behavior**
`OpenOpcService.exe` being able to provide the servers data

**Desktop (please complete the following information):**
 - OS: Windows Server 10.0.20348 Build 20348
 - Version 0.1.17

**Comment by renzop** [comment]
Yes we found out that the builded executables from the gihub action dont work. So you have to build it on a pc where the gbda_aut.dll is registered. Then it works. Does anyone have an idea how to register the dll on in the github action environment? Help would be apreciated.

**Comment by dieguscl** [comment]
I think I could make it work... I tested it in a fork and I had no issues whatsoever with the following modification on `build_exe.yml`:

```yml
name: Build EXE
on:
  create:
    tags:
      - "*.*.*"
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python (32-bit)
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
          architecture: x86
      - name: Install poetry
        uses: abatilo/actions-poetry@v3
      - name: Register gbda_aut.dll
        run: |
          Copy-Item .\lib\gbda_aut.dll C:\Windows\System32\
          regsvr32 /s C:\Windows\System32\gbda_aut.dll
        shell: pwsh
      - name: Install dependencies
        run: poetry install
      - name: Build executables
        run: scripts/build_executables.ps1
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            dist/OpenOpcCli.exe
            dist/OpenOpcServer.exe
            dist/OpenOpcService.exe
```
